# Generated by Django 4.2.3 on 2023-08-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisement',
        ),
    ]
